# Generated by Django 5.1.1 on 2024-09-18 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0001_initial'),
        ('services', '0005_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='inquiries.inquiries')),
                ('services', models.ManyToManyField(to='services.service')),
            ],
        ),
    ]
