# Generated by Django 5.1.1 on 2024-09-17 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_assigned_sales_agent'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'open'), ('In Progress', 'in progress'), ('Closed', 'closed')], default='Open', max_length=20)),
                ('assigned_sales_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('services', models.ManyToManyField(related_name='inquiries', to='services.service')),
            ],
        ),
    ]
