# Generated by Django 5.1.1 on 2024-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
