# Generated by Django 5.1.1 on 2024-09-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
